WIFI_SSID = <YOUR_WIFI_SSID>   # Network SSID
WIFI_PASS = <YOUR_WIFI_SSID>   # Network key
DEVICE_ID = b<YOUR_DEVICE_ID>  # From API KEYS PDF
CLOUD_PASSWORD = b<YOUR_CLOUD_PASSWORD> # From API KEYS PDF
